# tasks file for jenkins
- name: Task -1 Update APT package manager repositories cache # This is the name of the first task
  apt: # This module manages packages using apt
    update_cache: yes # This specifies that the APT package manager repositories cache should be updated

- name: Task -2 Install Java using Ansible # This is the name of the second task
  apt: # This module manages packages using apt
   name: "{{ packages }}" # This specifies that the packages listed in the 'packages' variable should be installed
   state: present # This specifies that the packages should be installed
  vars: # This defines variables for this task
    packages: # This defines a list of packages to install
       - openjdk-17-jdk # This specifies that the 'openjdk-17-jdk' package should be installed or other version also like java 11 or higher

- name: Task -3 ensure the jenkins apt repository key is installed # This is the name of the third task
  apt_key: # This module manages authentication keys used by apt to authenticate packages
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key # This specifies the URL of the key to install
    state: present # This specifies that the key should be installed

- name: Task -4 ensure the repository is configured # This is the name of the fourth task
  apt_repository: # This module manages APT repositories
    repo: deb https://pkg.jenkins.io/debian-stable binary/ # This specifies the repository to configure
    state: present # This specifies that the repository should be configured

- name: ensure jenkins is installed # This is the name of the fifth task
  apt: name=jenkins update_cache=yes # This installs Jenkins using apt and updates the cache

- name: ensure jenkins is running # This is the name of the sixth task
  service: name=jenkins state=started # This starts Jenkins as a service

- name: Display the password of jenkinsinstalliation # This is the name of the seventh task
  shell: cat  /var/lib/jenkins/secrets/initialAdminPassword # This runs a shell command to display Jenkins' initial admin password
  register: displaypass # This stores the output of the command in a variable called 'displaypass'
- debug: var=displaypass.stdout # This prints debugging information, specifically, it prints out Jenkins' initial admin password stored in 'displaypass.stdout'

