---
# tasks file for maven
# Update pkg cache
   - name: Update APT package manager repositories cache
     apt:
      update_cache: yes
#Java installation if not available  
   - name: Check if Java is installed
     command: java --version
     register: java_installed
     ignore_errors: yes
   - name: Install Java if not installed
     apt:
       name: '{{ packages }}'
       state: present
     when: java_installed.rc != 0
#Download maven file    
   - name: Download Apache Maven
     get_url: 
       url: '{{ maven_url }}' 
       dest: /opt/
#Unzip maven file
   - name: Unzip Apache Maven
     unarchive:
        src: /opt/{{zip_folder}}
        dest: /opt/
        remote_src: yes
#set mavenhome in order to use globally as localsystem/vm 
   - name: Set MAVEN_HOME
     lineinfile:
      dest: /etc/profile.d/maven.sh
      create: yes
      state: present
      mode: '0744'
      line: '{{ item }}'
     with_items:
         - 'export M2_HOME=/opt/{{unzip_foldername}}'
         - 'export PATH=${M2_HOME}/bin:${PATH}'
    
   - name: Check Maven installation status
     shell: bash -lc 'mvn --version'
     register: maven_version
     changed_when: False

   - name: Debug Maven version
     debug:
      msg: "{{ maven_version.stdout_lines[0] }}"
 
